apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-dockerfile-zq0s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-dockerfile-zq0s
    app.kubernetes.io/part-of: my-app123456
  name: python-dockerfile-zq0s
  namespace: jkopriva-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: python-dockerfile-zq0s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: python-dockerfile-zq0s
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:jkopriva-tenant-python-dockerfile-zq0s
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
